<a href="https://colab.research.google.com/github/k-messick/ds1002-vmv6mp/blob/main/homework/week-10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 10

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL to your notebook for review.

## Class Basics

Closely inspect the class below and answer the questions in the following cells.

In [94]:

class Products:
  def __init__(self, id, name, price, description, manufacturer):
    self.id = id
    self.name = name
    self.price = price
    self.description = description
    self.manufacturer = manufacturer

  def print_product(self):
    print(f"Product {self.id} is {self.name} made by {self.manufacturer}. It costs ${self.price}")


In [31]:
# What are the attributes of this class?

#Answer: The attributes of this class include id, name, price, description, and manufacturer.



In [95]:
# In one line of code, create an instance of the class populating its attributes.
Toys = Products(45899001,"Barbie", 21.99, "Popstar Barbie Doll", "Mattel")


In [96]:
# Referencing the instance you just created, what code is required to print out the name of the instance?
print(Toys.name)


Barbie


## Class Methods

In [97]:
# Using the instance you created above, call the `print_product` method properly in a line of code.
def print_product(self):
  print(f"Product {self.id} is {self.name} made by {self.manufacturer}. It costs ${self.price}.")

Toys.print_product()




Product 45899001 is Barbie made by Mattel. It costs $21.99


*I understand that the instructions say to call the 'print_product' method properly in a line of code, so I believe I would only need the #Toys.print_product() since it is already defined, however I included the def part as well in this case to show I understood where the line of code calling the method came from.

In [59]:
# Now declare the class again (copy + paste from above). But now add a NEW method that you write.
# This method should create a new attribute called "sales_price" that is 80% of the normal price.
#
# Finally, write this method to print out a statement like "The ________ product is on sale for _____"
# where you fill in the blanks with the name and sales_price of the product.


In [98]:
# Execute the class above
class Products:
  def __init__(self, id, name, price, description, manufacturer, sales_price):
    self.id = id
    self.name = name
    self.price = price
    self.description = description
    self.manufacturer = manufacturer
    self.sale = sales_price

  def sales_price(self):
    print(f"The {self.name} product is on sale for ${self.sale}.")


In [99]:
# Now create an instance of the class with new values.
Toys = Products(45899001,"Barbie", 21.99, "Popstar Barbie Doll", "Mattel", 17.59)



*Question: When you're creating an instance of a class with new values, is it better to do a new "name" too? Such as, #Discounted_Toys = Products(45899001,"Barbie", 21.99, "Popstar Barbie Doll", "Mattel", 17.59)


In [103]:
# Finally, using the instance you just created, invoke the new method you wrote. Be sure it prints
# the desired text described above.

Toys.sales_price()

The Barbie product is on sale for $17.59.
